### ISSUE TITLE
Menu softlock prevents you from accessing levels

### ISSUE THREAD

**Issue by Nextracer1** [TF2SR/Ronin#5]
### Bug
Seemingly at random you can get an infinite (but not frozen) loading screen. Both times this has happened to me it was on the first time i loaded a level in the session
Force disconnecting leads to an infinite loop of being kicked back to the main menu on loading any other level, and (potentially unrelated) doing it via the map command also does nothing

video: https://www.youtube.com/watch?v=IiWhCDj0ABg

### Steps to reproduce
1. attempt to play titanfall 2
2. pray

### Specifications
  - Ronin version: 1.0
  - Platform: EA App

**Comment by Clork9885** [comment]
probably not ronin issue
(TF2SR discord) https://discord.com/channels/241597846896377856/601933547913216008/1129766398873313363
get trolled

**Comment by zweek** [comment]
closing this for now since it seems to be an autosplitter bug
